// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO7tMa8LxgGPk4ah83yg4vF7aKUmAlmqU',
    appId: '1:234622831135:web:74900b7b473ff9be1d632a',
    messagingSenderId: '234622831135',
    projectId: 'mesclainvest-pi3',
    authDomain: 'mesclainvest-pi3.firebaseapp.com',
    storageBucket: 'mesclainvest-pi3.firebasestorage.app',
    measurementId: 'G-H87XRZ5H9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxVUtkNliqWTv3tUisugAdgHejSBRqLXM',
    appId: '1:234622831135:android:78e1b7f66d181cda1d632a',
    messagingSenderId: '234622831135',
    projectId: 'mesclainvest-pi3',
    storageBucket: 'mesclainvest-pi3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm0-H84XbZXjF6tNdwl1vVEBkjKsALBfE',
    appId: '1:234622831135:ios:f34eaa7b13c367a91d632a',
    messagingSenderId: '234622831135',
    projectId: 'mesclainvest-pi3',
    storageBucket: 'mesclainvest-pi3.firebasestorage.app',
    iosBundleId: 'com.mesclainvest.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm0-H84XbZXjF6tNdwl1vVEBkjKsALBfE',
    appId: '1:234622831135:ios:f34eaa7b13c367a91d632a',
    messagingSenderId: '234622831135',
    projectId: 'mesclainvest-pi3',
    storageBucket: 'mesclainvest-pi3.firebasestorage.app',
    iosBundleId: 'com.mesclainvest.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO7tMa8LxgGPk4ah83yg4vF7aKUmAlmqU',
    appId: '1:234622831135:web:beca5c9cc2e9cc201d632a',
    messagingSenderId: '234622831135',
    projectId: 'mesclainvest-pi3',
    authDomain: 'mesclainvest-pi3.firebaseapp.com',
    storageBucket: 'mesclainvest-pi3.firebasestorage.app',
    measurementId: 'G-TZDPRRQLKT',
  );
}
